name: Synchronize to forked repo - beta-test
on:
  push:
    branches:
      - beta-test

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta-test
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORKED_REPO_TOKEN }}
          fetch-depth: 0
          ref: beta-test

      - name: Add remote-url
        run: |
          git remote add forked-repo https://shchoon:${{ secrets.FORKED_REPO_TOKEN }}@github.com/shchoon/5Sense-FE
          git config user.name shchoon
          git config user.email acckr0604@gmail.com

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo beta-test

      - name: Clean up
        run: |
          git remote remove forked-repo